### ISSUE TITLE
Add Service List to Topic Detail

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-ux-ui#39]
### Description of design change:
Move service list onto the topic detail page, under topic "About" and above "Related Topics" 

### Rationale: 
Users had trouble recognizing the "Find services" FAB, and users want to be able to access services more quickly. Otherwise the app provides users no immediate value

### Difficulty, impact:
|--(technical difficulty)--| Very important to user |

### Possible Roadblocks:
- number of displayed services may be an issue, should it be 3 or?
- relates to "Service Detail" --> need to decide if it will link to a separate page or stay on the same page

### Visual reference: 
![TOPICDETAIL@2x.png]
(https://images.zenhubusercontent.com/5823860ee40e5714b1700133/85ba0d30-4f93-4d46-8abf-b9d3b5c145e7)

In Invision flow: https://invis.io/H7JJSDYKW5B#/335360341_TOPIC_DETAIL

**Comment by rasmus-storjohann-PG** [comment]
Need UX for saving services, and UX for accessing a service that is not saved (404)
1. Store just service id (bookmark), sucky offline UX
2. Recommended: Store contact info in permanent storage, no description
3. Store everything: Takes too much memory, no more work than #2
