### ISSUE TITLE
Search V1

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-ux-ui#55]
**Problem**
Need to make it easier for users to search for and find services/organizations. This is because:
- 1) Newcomers currently lack a direct route to find a service (can only go through topics). We do not amply serve newcomers who already know what they're looking for, or are seeking a service rather than orientation info;
- 2) Service list shows services that are within a 25 km radius of the geolocation of their mobile device. They are unable to find services from elsewhere;
- 3) It can be overwhelming to scroll through topics and they are not always intuitive ways to find the right service;
- 4) Service providers might find it challenging to find their services on the app to make sure that the information is up to date and accurate, as well as give feedback (related to Feedback module);

**Goal** - User/Job Stories
- As a user (newcomer or SPO staff), I want to search the entire service database and see organizations and services using keywords on my specific need (type of service) or full name of a specific service/organization.
- As a newcomer, I want to customize the location I use for the search, so I can conduct search even though I am not physically near where the search should be (eg. if I am outside the country).
- V1 of the search is only in English. As a user, if I am using the app in another language or try to search in another language, I want to get notified that the search is only available in English. 

**Important Questions**

**Pages/Flows**

**Updated Relevant Links**
- See full product spec: https://docs.google.com/document/d/1alwa7mx1_av2_Sc24t3VnlRwOu71pNGr5y1CBsCM3oc/edit?usp=sharing
- Existing UX inspo:
https://docs.google.com/presentation/d/1iuj4_9LH6HSfk4BWwbFDbw2G6ZxAPUW3MjmzghueYXo/edit?usp=sharing

**Comment by cherrielam** [comment]
## Sketches - Round 1

### Opening search from main bottom nav 

<img width="910" alt="Screen Shot 2019-07-05 at 1 20 53 PM" src="https://user-images.githubusercontent.com/21990736/60743860-33ea1d80-9f28-11e9-9acf-640c20d25b7b.png">

Alert upon opening search that it is only available in English. Alert can be dismissed (but stays there if search is open). **(Should alert be dismissed/permanent?)**

**Q: Does user see a list of all possible services upon opening search or nothing at all?**

### Location based search

<img width="838" alt="Screen Shot 2019-07-05 at 1 21 19 PM" src="https://user-images.githubusercontent.com/21990736/60743948-8b888900-9f28-11e9-8660-e5006e258931.png">

**Q: Should there be a map view of results? (eg. google maps style of search with lots of pins)
Q: Should there be a distance toggle?
Q: How should location be entered? Only drop pin or only words or both?** Most searches are text-based though, drop pin is rare

### Services vs. Organizations
Note diff between keyword search vs. matched organization vs. matched service name search. 
<img width="850" alt="Screen Shot 2019-07-05 at 1 22 40 PM" src="https://user-images.githubusercontent.com/21990736/60744014-d30f1500-9f28-11e9-9c7a-51188bf0459a.png">
<img width="629" alt="Screen Shot 2019-07-05 at 1 31 50 PM" src="https://user-images.githubusercontent.com/21990736/60744111-44e75e80-9f29-11e9-86eb-96f506baffd0.png">
<img width="900" alt="Screen Shot 2019-07-05 at 1 23 07 PM" src="https://user-images.githubusercontent.com/21990736/60744113-46b12200-9f29-11e9-8502-489c8f00648f.png">

**Comment by cherrielam** [comment]
- can we pop up an English only keyboard?
- do we necessarily want them to call BC211?

**Comment by cherrielam** [comment]
- user testing of bc211 database to understand what people are searching for and what successful search looks like

**Comment by cherrielam** [comment]
### Research
BC211 User Testing Results can be found here: https://drive.google.com/open?id=1B00VSn2_WZgXtABKfXNeoI1jff4j5VQNUZTnsw3svlo

## Sketches Round 2
- **Please review the screens and _notes_ in Zeplin, under the heading "Search (WIP)"** https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/dashboard?seid=5c476c88d2cd65386e4e49b2 (Teal blue notes are "Nice to have" features)

Changes from last round:
- slightly higher fidelity, more dev-ready layout
- added Org Detail page and Services Detail page to make a "dive in" experience rather than "search across" experience. The detail pages allow the user to view all other services from the same organization (This was a user-want that came out of the user research. Users by and large liked to be able to see the other services.)
- tried to make the UI simpler and more intuitive

**Comment by rasmus-storjohann-PG** [comment]
I feel it would be really helpful if you walked us through these mocks @cherrielam . It's hard to understand your thinking just from the pictures.

**Comment by cherrielam** [comment]
@rasmus-storjohann-PG Agree, I will book us a meeting for early next week.

**Comment by cherrielam** [comment]
As per discussion, next steps:

- [ ] testing plan for multilingual search interface
- [ ] amend the mocks per Arti & Rasmus feedback

**Comment by cherrielam** [comment]
Refer to https://github.com/pg-irc/pathways-frontend/issues/833 for mocks sent for development:

> The preliminary mocks are now available here. Please note that they are NOT recently tested, so implement with caution 🙂
> 
> ### Mocks
> 1. **Zeplin:** [**See mocks here**](https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/dashboard?seid=5c476c88d2cd65386e4e49b2) - please see section titled "Search (WIP)"
>    _Note: there are two versions of the search results screen: 1) [organization result & services results](https://zpl.io/VxrWMdw) and 2) [only shows services results](https://zpl.io/agWEZ09)_
> 2. **Click-through prototype** to see [flow](https://sketch.cloud/s/2k7wM/a/3pYK8D/play)
> 
> ### Notes/Disclaimers:
> * For the Search UI in other (non-English) languages --> the text within the search bar should say "Search for services (only in English)"
> * Grey box & Grey circle --> These are meant to be images of the organization, eg. Organization Logo. These are **nice to have**
> * Where it says: "Why is some information in English?" --> The flag to call BC211 has now been changed as a result of the findings from testing the partial localization. This change still **needs to be tested**
> * "Why is some information in English?" behaviour: should ONLY show in non-English languages
> * The tabs that toggle between "About" and "Services" on ORG DETAIL --> This is an attempt at showing the org detail and its services together without being an overwhelmingly long page. We are unclear yet if this is a usable/accessible yet. This **needs to be tested**
> * Bookmark and overflow menu --> early attempts of UI for saving, sharing etc. These **need to be tested**

Issue is now be tracked under the search epic: 
https://github.com/pg-irc/pathways-frontend/issues/850

**Comment by cherrielam** [comment]
Closing because now in frontend for production!
